/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dae4e5",
        "primary-fixed-dim": "#55d7ed",
        "inverse-on-surface": "#293233",
        "tertiary-fixed": "#ffdbc8",
        "outline": "#899293",
        "background": "#0c1516",
        "surface-bright": "#323b3c",
        "surface-tint": "#55d7ed",
        "on-surface-variant": "#bfc8c9",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#693b1c",
        "tertiary-fixed-dim": "#fbb88f",
        "on-primary-fixed-variant": "#004e59",
        "secondary-fixed": "#afedf3",
        "surface-container-high": "#222c2d",
        "tertiary-container": "#693b1c",
        "secondary": "#94d1d6",
        "on-tertiary": "#4e2508",
        "tertiary": "#fbb88f",
        "surface-container-lowest": "#071011",
        "surface-dim": "#0c1516",
        "on-primary-fixed": "#001f24",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#141d1e",
        "surface-container": "#182122",
        "surface": "#0c1516",
        "error-container": "#93000a",
        "secondary-container": "#004f54",
        "secondary-fixed-dim": "#94d1d6",
        "on-secondary-container": "#82bfc5",
        "on-tertiary-container": "#e8a77f",
        "on-background": "#dae4e5",
        "surface-variant": "#2d3637",
        "on-secondary-fixed": "#002022",
        "on-secondary": "#00363a",
        "on-surface": "#dae4e5",
        "primary-container": "#004e59",
        "outline-variant": "#3f4849",
        "primary-fixed": "#9eefff",
        "on-primary": "#00363e",
        "on-secondary-fixed-variant": "#004f54",
        "on-error": "#690005",
        "on-tertiary-fixed": "#321300",
        "surface-container-highest": "#2d3637",
        "primary": "#55d7ed",
        "inverse-primary": "#006876",
        "on-primary-container": "#3dc5db"
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
  darkMode: "class",
};
